### ISSUE TITLE
13: Add column widths to tables

### ISSUE THREAD

**Issue by wavegate** [wavegate/resmatch#13]
Right now almost every column has the same width, as the default by AG Grid

We can apply better widths so bigger fields can have more space

Note that users CAN resize columns, but it would be annoying for them to have to do that every time

Difficulty: Easy
Impact: High

**Comment by wavegate** [comment]
I've resized the Invite page columns

**Comment by ehuang47** [comment]
This will be worked on in a series of PRs. The [first PR](https://github.com/wavegate/resmatch/pull/55) is scoped to interview invite & rejection tables.
