### ISSUE TITLE
28: user login friction

### ISSUE THREAD

**Issue by ehuang47** [wavegate/resmatch#28]
Users aren't willing to create an account on the website for possibly a couple reasons:

1. Too lazy
2. Not willing to link their email 
3. Not willing to expose their information
4. Spreadsheet is more flexible (can go incognito and freely edit

Need to figure out how to address this to convert as many spreadsheet users to the website.
Goal: website replaces the spreadsheet

**Comment by wavegate** [comment]
we've done the best we can for now. will reopen if new ideas surface
